recipeId: Pizza cojonuda
description: Pizza con vegetales famosa del restaurante Luna Rossa
ingredients: Mozzarella fresca, Gorgonzola DOP, spianata picante calabres, setas boletus.
complexity: dificil
